### ISSUE TITLE
Transaction creation and submission.

### ISSUE THREAD

**Issue by CryptoCurrencyStuff** [AaronJaramillo/LibbitcoinTutorial#1]
Due to the lack of libbitcoin documentation for recent versions I came across your HD wallet turorials, I'm wondering if you would consider adding an example which shows the process of creating and submitting a transaction to the p2p network.

**Comment by AaronJaramillo** [comment]
I added an example of creating a raw transaction in the /rawTX directory.

**Comment by AaronJaramillo** [comment]
I added the functionality to broadcast transactions to the rawTX script. It's pretty straight forward if you look at the code, but a blog post about it will be posted to [my blog](www.aaronjaramillo.com) soon. keep in mind you'll need to have libbitcoin-client installed to interact with the p2p network.
